function Hd = test
%TEST Returns a discrete-time filter object.

%
% M-File generated by MATLAB(R) 7.5 and the Signal Processing Toolbox 6.8.
%
% Generated on: 25-Jan-2012 23:55:11
%

% Butterworth Lowpass filter designed using FDESIGN.LOWPASS.

% All frequency values are in Hz.
Fs = 48000;  % Sampling Frequency

N  = 6;      % Order
Fc = 10800;  % Cutoff Frequency

% Construct an FDESIGN object and call its BUTTER method.
h  = fdesign.lowpass('N,Fc', N, Fc, Fs);
Hd = design(h, 'butter');
set(Hd, 'Arithmetic', 'double');

% [EOF]
